### ISSUE TITLE
SDK does not work with Xcode 9 beta 3

### ISSUE THREAD

**Issue by dhoskins** [localz/Spotz3-iOS-SDK#2]
`SpotzSDK` has a dependency on `YapDatabase/Standard/Core`, which itself has a dependency on `CocoaLumberjack`.

However CocoaLumberjack has a conflict with Xcode 9 beta 3 as described here: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/883

As such SpotzSDK cannot currently be used with Xcode 9 beta 3.

**Comment by dsykesturner** [comment]
Hi @dhoskins, thanks for pointing that out! 

CocoaLumberjack has pushed a fix to their master branch but hasn't tagged it into a version release just yet, so while waiting could you try adding the following to your podfile?

`pod 'CocoaLumberjack', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'master'`


Ref: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/882

**Comment by dhoskins** [comment]
Thanks, didn't realise it was that simple.

TIL you cannot have multiple versions of a single Cocoapod in your project.
